[package]
name = "rust-dbf-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
dbase = "0.3.0"
serde = "1.0.164"
serde_derive = "1.0.164"
serde_json = "1.0.99"
toml = "0.7.5"
